### PR TITLE
Relax origin validation (bug 1065181)

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by andymckay** [comment]
Will the receipts and in-app products still work ok since they use origin?

**Comment by kumar303** [comment]
> Will the receipts and in-app products still work ok since they use origin?

I don't see why not because when an app is uploaded with origin ``app://random-string`` then its domain is set to ``random-string`` and that's the key for all all things related to in-app purchases. Since ``random-string`` is a perfectly valid custom origin on the platform then everything should work.

The main reason we need this patch is because in-app purchases are designed to work without a server. If an app doesn't have a server then it's confusing if Marketplace tells them their origin should "look like a domain they own." There is really no reason it should like a real domain except for cases when we want to prevent apps from stealing facebook.com or whatever. As pointed out in the discussion thread linked in the bug, preventing domain stealing is out of scope for automatic origin validation. App reviewers will do that kind of validation themselves.

**Comment by kumar303** [comment]
@cvan or @diox r?

**Comment by diox** [comment]
This makes sense. Have you checked if zamboni has rules of its own ? **r+** with that in mind.

**Comment by kumar303** [comment]
@diox thanks for the r. I don't think zamboni has its own rules but in any case this patch is step 1 so let me merge it and see! I will follow up with another patch if needed.

**Pull request merged**
